version: '1.0'
services:
  fw:
    # id del servicio
    image: fw # nombre de la imagen
    build: ./fw # ruta del Dockerfile
    container_name: fw # identificador
    networks:
      # id. de la red/es a las que pertenece el contenedor
      extranet:
        ipv4_address: 10.5.0.1
      DMZ:
        ipv4_address: 10.5.1.1
      intranet:
        ipv4_address: 10.5.2.1
    privileged: true
    tty: true

  ext1:
    image: external1
    build: ./extranet
    container_name: ext1
    networks:
      external-network:
        ipv4_address: 10.5.0.20 # ip estática
    depends_on:
      - fw # Dependencias
    privileged: true
    tty: true

  dmz1:
    image: dmz1
    build: ./dmz/dmz1
    container_name: dmz1
    networks:
      DMZ:
        ipv4_address: 10.5.1.20 # ip estática
    depends_on:
      - fw
    privileged: true
    tty: true

  dmz2:
    image: dmz2
    build: ./dmz/dmz2
    container_name: dmz2
    networks:
      DMZ:
        ipv4_address: 10.5.1.21 # ip estática
    depends_on:
      - fw
    privileged: true
    tty: true

  int1:
    image: internal1
    build: ./intranet/int12
    container_name: int1
    networks:
      internal-network:
        ipv4_address: 10.5.2.20 # ip estática
    depends_on:
      - fw
    privileged: true
    tty: true

  int2:
    image: internal2
    build: ./intranet/int12
    container_name: int2
    networks:
      internal-network:
        ipv4_address: 10.5.2.21 # ip estática
    depends_on:
      - fw
    privileged: true
    tty: true

int3:
  image: internal3
  build: ./intranet/int3
  container_name: int3
  networks:
    internal-network:
      ipv4_address: 10.5.2.22 # ip estática
  depends_on:
    - fw
  privileged: true
  tty: true

networks:
  extranet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.254

  DMZ:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.254

  intranet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.254
